{
	"version": 1556161349,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/playerpistol-sheet0.png",
		"images/blood-sheet0.png",
		"images/zombie-sheet0.png",
		"images/zombie-sheet1.png",
		"images/explosion-sheet0.png",
		"images/bullets-sheet0.png",
		"images/playerflashlight-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/playerknife-sheet0.png",
		"images/ammo-sheet0.png",
		"images/playerak-sheet0.png",
		"images/ak-sheet0.png",
		"images/bulletsak2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground2.png",
		"images/bloodunderline-sheet0.png",
		"images/startbutton-sheet0.png",
		"images/storybackground-sheet0.png",
		"images/mouse2-sheet0.png",
		"images/arrowkeys-sheet0.png",
		"images/continue-sheet0.png",
		"images/gameover-sheet0.png",
		"images/reset-sheet0.png",
		"images/restart-sheet0.png",
		"images/restart2-sheet0.png",
		"images/mainbackground-sheet0.png",
		"media/ak 47 bullet.ogg",
		"media/bullet shell.ogg",
		"media/explosion.ogg",
		"media/omaewamoushindeiru.ogg",
		"media/pistol bullet.ogg",
		"media/knife slash.ogg",
		"media/soundtrack.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}